#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : R-lhs
Version  : 1.2.0
Release  : 53
URL      : https://cran.r-project.org/src/contrib/lhs_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lhs_1.2.0.tar.gz
Summary  : Latin Hypercube Samples
Group    : Development/Tools
License  : GPL-3.0
Requires: R-lhs-lib = %{version}-%{release}
Requires: R-Rcpp
BuildRequires : R-Rcpp
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-lhs package.
Group: Libraries

%description lib
lib components for the R-lhs package.


%prep
%setup -q -n lhs
pushd ..
cp -a lhs buildavx2
popd
pushd ..
cp -a lhs buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719947482

%install
export SOURCE_DATE_EPOCH=1719947482
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lhs/DESCRIPTION
/usr/lib64/R/library/lhs/INDEX
/usr/lib64/R/library/lhs/Meta/Rd.rds
/usr/lib64/R/library/lhs/Meta/features.rds
/usr/lib64/R/library/lhs/Meta/hsearch.rds
/usr/lib64/R/library/lhs/Meta/links.rds
/usr/lib64/R/library/lhs/Meta/nsInfo.rds
/usr/lib64/R/library/lhs/Meta/package.rds
/usr/lib64/R/library/lhs/Meta/vignette.rds
/usr/lib64/R/library/lhs/NAMESPACE
/usr/lib64/R/library/lhs/NEWS
/usr/lib64/R/library/lhs/R/lhs
/usr/lib64/R/library/lhs/R/lhs.rdb
/usr/lib64/R/library/lhs/R/lhs.rdx
/usr/lib64/R/library/lhs/doc/augment_lhs.R
/usr/lib64/R/library/lhs/doc/augment_lhs.Rmd
/usr/lib64/R/library/lhs/doc/augment_lhs.html
/usr/lib64/R/library/lhs/doc/correlated_lhs.R
/usr/lib64/R/library/lhs/doc/correlated_lhs.Rmd
/usr/lib64/R/library/lhs/doc/correlated_lhs.html
/usr/lib64/R/library/lhs/doc/index.html
/usr/lib64/R/library/lhs/doc/lhs_basics.R
/usr/lib64/R/library/lhs/doc/lhs_basics.Rmd
/usr/lib64/R/library/lhs/doc/lhs_basics.html
/usr/lib64/R/library/lhs/doc/lhs_faq.R
/usr/lib64/R/library/lhs/doc/lhs_faq.Rmd
/usr/lib64/R/library/lhs/doc/lhs_faq.html
/usr/lib64/R/library/lhs/help/AnIndex
/usr/lib64/R/library/lhs/help/aliases.rds
/usr/lib64/R/library/lhs/help/lhs.rdb
/usr/lib64/R/library/lhs/help/lhs.rdx
/usr/lib64/R/library/lhs/help/paths.rds
/usr/lib64/R/library/lhs/html/00Index.html
/usr/lib64/R/library/lhs/html/R.css
/usr/lib64/R/library/lhs/tests/testthat.R
/usr/lib64/R/library/lhs/tests/testthat/helper-lhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-augmentlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-correlatedLHS.R
/usr/lib64/R/library/lhs/tests/testthat/test-create_oalhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-createoa.R
/usr/lib64/R/library/lhs/tests/testthat/test-galois_field.R
/usr/lib64/R/library/lhs/tests/testthat/test-geneticlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-get_library_versions.R
/usr/lib64/R/library/lhs/tests/testthat/test-improvedlhs.r
/usr/lib64/R/library/lhs/tests/testthat/test-maximinlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-oa_to_oalhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-optaugmentlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-optimumlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-optseededlhs.R
/usr/lib64/R/library/lhs/tests/testthat/test-quantile_transforms.R
/usr/lib64/R/library/lhs/tests/testthat/test-randomlhs.r

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/lhs/libs/lhs.so
/V4/usr/lib64/R/library/lhs/libs/lhs.so
/usr/lib64/R/library/lhs/libs/lhs.so
